<?xml version="1.0"?>
<robot name="robot_with_scanner" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- PARAMETERS -->
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width"  value="0.05"/>
  <xacro:property name="half_width"   value="0.20"/>
  <xacro:property name="wheelbase"    value="0.30"/>

  <!-- ================= BASE ================= -->
  <link name="base_link">
    <inertial>
      <mass value="10.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.4" iyy="0.4" izz="0.4" ixy="0" ixz="0" iyz="0"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${wheel_radius+0.15}" />
      <geometry><box size="0.6 0.4 0.3"/></geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${wheel_radius+0.15}" />
      <geometry><box size="0.6 0.4 0.3"/></geometry>
    </collision>
  </link>

  <!-- MACRO FOR WHEEL -->
  <xacro:macro name="wheel_link" params="name">
    <link name="${name}">
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- WHEELS -->
  <xacro:wheel_link name="front_left_wheel"/>
  <xacro:wheel_link name="front_right_wheel"/>
  <xacro:wheel_link name="rear_left_wheel"/>
  <xacro:wheel_link name="rear_right_wheel"/>

  <!-- JOINTS -->
  <joint name="front_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="front_left_wheel"/>
    <origin xyz="${wheelbase} ${half_width} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="front_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="front_right_wheel"/>
    <origin xyz="${wheelbase} -${half_width} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="rear_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="rear_left_wheel"/>
    <origin xyz="-${wheelbase} ${half_width} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="rear_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="rear_right_wheel"/>
    <origin xyz="-${wheelbase} -${half_width} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- DIFF DRIVE -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <leftJoint>rear_left_joint</leftJoint>
      <rightJoint>rear_right_joint</rightJoint>
      <wheelSeparation>${2*half_width}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <publishTf>true</publishTf>
    </plugin>
  </gazebo>

  <!-- SCANNER -->
<link name="vertical_profiler_link">
  <inertial>
    <mass value="0.2"/>
    <origin xyz="0 0 0"/>
    <inertia
      ixx="0.001" ixy="0.0" ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001"/>
  </inertial>

  <visual>
    <geometry><box size="0.05 0.05 0.05"/></geometry>
  </visual>

  <collision>
    <geometry><box size="0.05 0.05 0.05"/></geometry>
  </collision>
</link>

<joint name="scanner_joint" type="fixed">
  <parent link="base_link"/>
  <child  link="vertical_profiler_link"/>
  <origin xyz="0 0 0.8" rpy="1.5708 0 1.5708"/>
</joint>

<gazebo reference="vertical_profiler_link">
  <sensor type="ray" name="vertical_laser">
    <always_on>true</always_on>
    <update_rate>30</update_rate>
    <visualize>true</visualize>

    <ray>
      <scan>
        <!-- The vertical scan is achieved by rotating the link. -->
        <horizontal>
          <samples>300</samples>
          <resolution>1</resolution>
          <min_angle>-0.25</min_angle>
          <max_angle>0.25</max_angle>
        </horizontal>
      </scan>

      <range>
        <min>0.1</min>
        <max>6.0</max>
        <resolution>0.001</resolution>
      </range>
    </ray>

    <plugin name="gazebo_ros_vertical_scanner" filename="libgazebo_ros_laser.so">
      <topicName>/scan_cloud</topicName>
      <frameName>vertical_profiler_link</frameName>
    </plugin>
  </sensor>
</gazebo>

  

</robot>
